version: '3.8'

services:

  db:
    container_name : postgres_arnau
    image: postgres:latest
    environment:
      POSTGRES_USER: arnau
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres_arnau_database
    ports:
      - "5432:5432"
    networks : 
      - arnau_app_network
 
  app:
    container_name: node_arnau
    build: ./app/
    ports:
      - "3000:3000"
    env_file:
      - ./app/.env
    depends_on:
      - db
    command: ["sh", "-c", "npx prisma migrate deploy && npm start"]
    networks : 
      - arnau_app_network

volumes : 
  postgres_data :



networks:
  arnau_app_network:
    driver: bridge
